### ISSUE TITLE
unpickling error

### ISSUE THREAD

**Issue by linnabraham** [bnaul/IrregularTimeSeriesAutoencoderPaper#3]
Trying to run the script on python 3 using the following command:

run survey_classifier.py --size 10 --num_layers 5 --model_type GRU --survey_files data/macho/full.pkl --drop_frac 0.5 --lr 0.0001 --sim_type train

gives me an error related to unpickling in the joblib.load line.
Has the pickling been done using python2?

KeyError                                  Traceback (most recent call last)

/content/IrregularTimeSeriesAutoencoderPaper/survey_classifier.py in <module>()
    104 
    105 if __name__ == '__main__':
--> 106     X, X_raw, Y, model, args = main()

4 frames

/content/IrregularTimeSeriesAutoencoderPaper/survey_classifier.py in main(args)
     31     classes = ['RR_Lyrae_FM', 'W_Ursae_Maj', 'Classical_Cepheid',
     32                'Beta_Persei', 'Semireg_PV']
---> 33     lc_lists = [joblib.load(f) for f in args.survey_files]
     34     combined = [lc for lc_list in lc_lists for lc in lc_list]
     35     combined = [lc for lc in combined if lc.label in classes]

/content/IrregularTimeSeriesAutoencoderPaper/survey_classifier.py in <listcomp>(.0)
     31     classes = ['RR_Lyrae_FM', 'W_Ursae_Maj', 'Classical_Cepheid',
     32                'Beta_Persei', 'Semireg_PV']
---> 33     lc_lists = [joblib.load(f) for f in args.survey_files]
     34     combined = [lc for lc_list in lc_lists for lc in lc_list]
     35     combined = [lc for lc in combined if lc.label in classes]

/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py in load(filename, mmap_mode)
    596                     return load_compatibility(fobj)
    597 
--> 598                 obj = _unpickle(fobj, filename, mmap_mode)
    599 
    600     return obj

/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    524     obj = None
    525     try:
--> 526         obj = unpickler.load()
    527         if unpickler.compat_mode:
    528             warnings.warn("The file '%s' has been generated with a "

/usr/lib/python3.6/pickle.py in load(self)
   1048                     raise EOFError
   1049                 assert isinstance(key, bytes_types)
-> 1050                 dispatch[key[0]](self)
   1051         except _Stop as stopinst:
   1052             return stopinst.value

**Comment by bnaul** [comment]
Can you try {up,down}grading to `joblib==0.11`?

**Comment by bnaul** [comment]
Update: actually the data is no longer present, but it's now mirrored at https://gitlab.com/cesium-ml/IrregularTimeSeriesAutoencoderPaper.

**Comment by linnabraham** [comment]
The same problem persists. Even after cloning from gitlab, I note that the
file size for data/linear/full.pkl hasnt changed.


Linn
